### ISSUE TITLE
Cannot run CVparser main if one of docx or doc file is open.

### ISSUE THREAD

**Issue by tramyardg** [tramyardg/CVparser#5]
Error:
```
[main] ERROR com.cv.parser.CVparserMain - main
java.lang.NullPointerException
	at com.cv.parser.extract.MSExtractor.extractFiles(MSExtractor.java:74)
	at com.cv.parser.extract.MSExtractor.main(MSExtractor.java:43)
	at com.cv.parser.CVparserMain.createContents(CVparserMain.java:137)
	at com.cv.parser.CVparserMain.open(CVparserMain.java:51)
	at com.cv.parser.CVparserMain.main(CVparserMain.java:39)
```

**Comment by tramyardg** [comment]
Instead, show a dialog if one or more open Microsoft Word files are open.
